[package]
name = "polodb_core"
version = "2.0.0"
authors = ["Vincent Chan <okcdz@diverse.space>"]
license = "MIT"
edition = "2018"
repository = "https://github.com/vincentdchan/PoloDB"
description = "PoloDB is an embedded JSON-based database"
keywords = ["database", "embedded", "cross-platform"]

[lib]
name="polodb_core"
path="lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
lru = "0.7.0"
# polodb_bson = "2.0.0"
polodb_bson = { path = "../polodb_bson" }
crc64fast = "1.0"
hashbrown = "0.11.2"
getrandom = "0.2.3"
byteorder = "1.4.3"
num_enum = "0.5.4"

[dev-dependencies]
polodb_line_diff = { path = "../polodb_line_diff" }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["fileapi", "namedpipeapi"] }
